apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-logging-operator
  labels:
spec:
 replicas: 1
 selector:
   matchLabels:
     name: cluster-logging-operator
 template:
   metadata:
     annotations:
       target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
     labels:
       name: cluster-logging-operator
   spec:
     containers:
     - command:
       - cluster-logging-operator
       env:
       - name: WATCH_NAMESPACE
         valueFrom:
           fieldRef:
             fieldPath: metadata.annotations['olm.targetNamespaces']
       - name: POD_NAME
         valueFrom:
           fieldRef:
             fieldPath: metadata.name
       - name: OPERATOR_NAME
         value: cluster-logging-operator
       image: controller
       imagePullPolicy: IfNotPresent
       name: cluster-logging-operator
       resources: {}
     nodeSelector:
       kubernetes.io/os: linux
     serviceAccountName: cluster-logging-operator
