resources:
- log-collector-privileged_role.yaml
- log_collector_privileged_binding.yaml
- metadata_reader_clusterrole.yaml
- metadata_reader_clusterrolebinding.yaml
- prometheus_role.yaml
- prometheus_role_binding.yaml
- role.yaml
- role_binding.yaml
- service_account.yaml
