# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/logging.openshift.io_clusterlogforwarders.yaml
- bases/logging.openshift.io_clusterloggings.yaml
# +kubebuilder:scaffold:crdkustomizeresource

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml

patchesJson6902:
- path: patches/crd-v1-singleton-patch.yaml
  target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: clusterlogforwarders.logging.openshift.io
- path: patches/crd-v1-clusterloggings-patches.yaml
  target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: clusterloggings.logging.openshift.io
